language: nix

env:
  - PROJECT=apidoc-th  COMPILER=ghc7103
  - PROJECT=apidoc-th  COMPILER=ghc802
  - PROJECT=apidoc-th  COMPILER=ghcHEAD
  - PROJECT=apidoc-cli COMPILER=ghc7103
  - PROJECT=apidoc-cli COMPILER=ghc802
  - PROJECT=apidoc-cli COMPILER=ghcHEAD

script: travis_wait 30 nix-build $PROJECT/default.nix -A pkg
