sudo: false
language: generic

env:
  - PACKAGE=apidoc-th
  - PACKAGE=apidoc-cli

cache:
  directories:
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --stack-yaml $PACKAGE/stack.yaml --no-terminal --install-ghc test --only-dependencies

script:
  - stack --stack-yaml $PACKAGE/stack.yaml --no-terminal test --haddock --no-haddock-deps
